# Generated by Django 6.1.1 on 2026-09-22 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('finding', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_reports', to='ingestion.contract')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigation Report',
                'verbose_name_plural': 'Investigation Reports',
                'db_table': 'investigation_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
