# Generated by Django 6.1.1 on 2026-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('explanation_id', models.AutoField(primary_key=True, serialize=False)),
                ('shap_values', models.JSONField()),
                ('feature_importance', models.JSONField()),
                ('force_plot_data', models.JSONField(blank=True, null=True)),
                ('natural_language', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='ingestion.contract')),
            ],
            options={
                'verbose_name': 'Explanation',
                'verbose_name_plural': 'Explanations',
                'db_table': 'explanations',
            },
        ),
    ]
