# Generated by Django 6.1.1 on 2026-09-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='model_used',
            field=models.CharField(default='isolation_forest', max_length=50),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='ingestion.contract'),
        ),
        migrations.AlterUniqueTogether(
            name='explanation',
            unique_together={('contract', 'model_used')},
        ),
    ]
