# Generated by Django 6.1.1 on 2026-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcuringEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Procuring Entity',
                'verbose_name_plural': 'Procuring Entities',
                'db_table': 'procuring_entities',
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=255)),
                ('ocds_release', models.JSONField()),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Raw Record',
                'verbose_name_plural': 'Raw Records',
                'db_table': 'raw_records',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cac_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('bidding_window_days', models.IntegerField(blank=True, null=True)),
                ('num_bidders', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nocopo_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='ingestion.procuringentity')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='ingestion.vendor')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
            },
        ),
    ]
