# Generated by Django 6.1.1 on 2026-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_deviation', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('single_bidder_flag', models.BooleanField(default=False)),
                ('vendor_win_frequency', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('vendor_win_concentration', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('splitting_flag', models.BooleanField(default=False)),
                ('splitting_count', models.IntegerField(default=0)),
                ('log_contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ingestion.contract')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'features',
            },
        ),
    ]
