# Generated by Django 6.1.1 on 2026-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=6, max_digits=8)),
                ('model_used', models.CharField(max_length=50)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='ingestion.contract')),
            ],
            options={
                'verbose_name': 'Anomaly Flag',
                'verbose_name_plural': 'Anomaly Flags',
                'db_table': 'anomaly_flags',
            },
        ),
    ]
