# Generated by Django 6.1.1 on 2026-09-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('contamination', models.FloatField(default=0.05)),
                ('n_samples', models.IntegerField(default=0)),
                ('n_features', models.IntegerField(default=0)),
                ('n_anomalies', models.IntegerField(default=0)),
                ('score_mean', models.FloatField(blank=True, null=True)),
                ('score_std', models.FloatField(blank=True, null=True)),
                ('score_min', models.FloatField(blank=True, null=True)),
                ('score_max', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'db_table': 'analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
