# Generated by Django 6.1.1 on 2026-09-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_analysisrun'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyflag',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_flags', to='ingestion.contract'),
        ),
        migrations.AlterUniqueTogether(
            name='anomalyflag',
            unique_together={('contract', 'model_used')},
        ),
    ]
